#!/bin/bash
#
# SeqDB - storage model for Next Generation Sequencing data
#
# Copyright 2011-2012, Brown University, Providence, RI. All Rights Reserved.
#
# This file is part of SeqDB.
#
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose other than its incorporation into a
# commercial product is hereby granted without fee, provided that the
# above copyright notice appear in all copies and that both that
# copyright notice and this permission notice appear in supporting
# documentation, and that the name of Brown University not be used in
# advertising or publicity pertaining to distribution of the software
# without specific, written prior permission.
#
# BROWN UNIVERSITY DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR ANY
# PARTICULAR PURPOSE.  IN NO EVENT SHALL BROWN UNIVERSITY BE LIABLE FOR
# ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

if [ $# -lt 2 ]; then
	echo "usage: seqdb-mount SEQDB_FILE MOUNT_PATH" >&2
	exit 0
fi

FILE=$1
MOUNT=$2

FSTAB=$HOME/.seqdb.fstab
touch $FSTAB

set -o nounset
#set -o errexit

echo -e "\nseqdb-mount: mounting $FILE at $MOUNT" >&2
if [ -e $MOUNT ]; then
	echo "seqdb-mount: error: mount point already exists:
  $MOUNT
  Please unmount first, or move the file if it isn't a previous seqdb mount." >&2
	exit 1
else
	mkfifo $MOUNT
	echo "$$	$FILE	$MOUNT" >> $FSTAB
fi
seqdb-extract $FILE >$MOUNT
echo -e "\nseqdb-mount: reached end of $FILE, unmounting $MOUNT" >&2
rm $MOUNT
sed -i -e /^$$/d $FSTAB

